CREATE USER ANDREY_GABO_CHAMO_JOSE IDENTIFIED BY AGCJ123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, CREATE VIEW TO ANDREY_GABO_CHAMO_JOSE;

ALTER USER ANDREY_GABO_CHAMO_JOSE QUOTA UNLIMITED ON users;

CREATE USER BACKEND_CON IDENTIFIED BY Abr07;

GRANT CREATE SESSION TO BACKEND_CON;

DECLARE
    CURSOR c_tables IS
        SELECT table_name
        FROM all_tables
        WHERE owner = 'ANDREY_GABO_CHAMO_JOSE';

    v_sql VARCHAR2(500);
    v_privilegio VARCHAR2(50) := 'DELETE';
    v_usuario VARCHAR2(50) := 'BACKEND_CON';

BEGIN
    FOR r_table IN c_tables LOOP
        v_sql := 'GRANT ' || v_privilegio || ' ON ANDREY_GABO_CHAMO_JOSE.' || r_table.table_name || ' TO ' || v_usuario;

        DBMS_OUTPUT.PUT_LINE(v_sql || ';');
        EXECUTE IMMEDIATE v_sql;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Proceso de otorgamiento de permisos completado.');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al procesar: ' || SQLERRM);
END;
/



GRANT EXECUTE ON PKG_GESTION_USUARIOS TO BACKEND_CON;
GRANT EXECUTE ON PKG_GESTION_DIRECCIONES TO BACKEND_CON;
GRANT EXECUTE ON PKG_GESTION_ROLES TO BACKEND_CON;

GRANT EXECUTE ON PKG_PRODUCTO TO BACKEND_CON;
GRANT EXECUTE ON PKG_STOCK TO BACKEND_CON;
GRANT EXECUTE ON PKG_CATEGORIA TO BACKEND_CON;
GRANT EXECUTE ON PKG_REPORTES_STOCK TO BACKEND_CON;

GRANT EXECUTE ON PKG_ANALYTICS_VENTAS TO BACKEND_CON;
GRANT EXECUTE ON PKG_GESTION_PRODUCTOS_PROV TO BACKEND_CON;


GRANT EXECUTE ON INGRESOS_PKG TO BACKEND_CON;
GRANT EXECUTE ON FACTURAS_PKG TO BACKEND_CON;

GRANT EXECUTE ON PKG_CARRITO TO BACKEND_CON;
GRANT EXECUTE ON PKG_VENTAS TO BACKEND_CON;

SELECT
    GRANTEE,
    OWNER AS TABLE_OWNER,
    TABLE_NAME,
    PRIVILEGE,
    GRANTABLE
FROM
    DBA_TAB_PRIVS
WHERE
    GRANTEE = 'BACKEND_CON'
ORDER BY
    OWNER, TABLE_NAME, PRIVILEGE;