CREATE USER ANDREY_GABO_CHAMO_JOSE IDENTIFIED BY AGCJ123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, CREATE VIEW TO ANDREY_GABO_CHAMO_JOSE;

ALTER USER ANDREY_GABO_CHAMO_JOSE QUOTA UNLIMITED ON users;