CREATE USER ANDREY_GABO_CHAMO_JOSE IDENTIFIED BY AGCJ123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, CREATE VIEW TO ANDREY_GABO_CHAMO_JOSE;

ALTER USER ANDREY_GABO_CHAMO_JOSE QUOTA UNLIMITED ON users;

CREATE USER BACKEND_CON IDENTIFIED BY Abr07;

GRANT CREATE SESSION TO BACKEND_CON;

DECLARE
    v_sql VARCHAR2(500);
BEGIN
    FOR t IN (
        SELECT table_name 
        FROM all_tables
        WHERE owner = 'ANDREY_GABO_CHAMO_JOSE'
    ) LOOP
        v_sql := 'GRANT ALL PRIVILEGES ON ANDREY_GABO_CHAMO_JOSE.' 
                 || t.table_name 
                 || ' TO BACKEND_CON';

        EXECUTE IMMEDIATE v_sql;
    END LOOP;
END;
/

DECLARE
    v_sql VARCHAR2(500);
BEGIN
    FOR pkg IN (
        SELECT object_name
        FROM all_objects
        WHERE owner = 'ANDREY_GABO_CHAMO_JOSE'
          AND object_type = 'PACKAGE'
    ) LOOP
        v_sql := 'GRANT EXECUTE ON ANDREY_GABO_CHAMO_JOSE.' || pkg.object_name || ' TO BACKEND_CON';
        EXECUTE IMMEDIATE v_sql;
    END LOOP;
END;
/



GRANT EXECUTE ON PKG_GESTION_USUARIOS TO BACKEND_CON;
GRANT EXECUTE ON PKG_GESTION_DIRECCIONES TO BACKEND_CON;
GRANT EXECUTE ON PKG_GESTION_ROLES TO BACKEND_CON;

GRANT EXECUTE ON PKG_PRODUCTO TO BACKEND_CON;
GRANT EXECUTE ON PKG_STOCK TO BACKEND_CON;
GRANT EXECUTE ON PKG_CATEGORIA TO BACKEND_CON;
GRANT EXECUTE ON PKG_REPORTES_STOCK TO BACKEND_CON;

GRANT EXECUTE ON PKG_ANALYTICS_VENTAS TO BACKEND_CON;
GRANT EXECUTE ON PKG_GESTION_PRODUCTOS_PROV TO BACKEND_CON;


GRANT EXECUTE ON INGRESOS_PKG TO BACKEND_CON;
GRANT EXECUTE ON FACTURAS_PKG TO BACKEND_CON;

GRANT EXECUTE ON PKG_CARRITO TO BACKEND_CON;
GRANT EXECUTE ON PKG_VENTAS TO BACKEND_CON;
