CREATE OR REPLACE VIEW vw_ingresos_base AS
SELECT 
    id_ingreso,
    sucursal_id,
    descripcion,
    monto,
    fecha_recibido,
    registrado_por,
    tipo
FROM ingresos;

--  VISTAS 2 GABRIEL
CREATE OR REPLACE VIEW vw_ingresos_por_fecha AS
SELECT 
    id_ingreso,
    descripcion,
    monto,
    fecha_recibido
FROM ingresos;


--  VISTAS 3 GABRIEL
SELECT * FROM vw_ingresos_por_fecha
WHERE fecha_recibido BETWEEN p_fecha_inicio AND p_fecha_fin
ORDER BY fecha_recibido;


--  VISTAS 4 GABRIEL
CREATE OR REPLACE VIEW vw_gastos_base AS
SELECT 
    id_gasto,
    descripcion,
    monto,
    categoria,
    fecha_ocurrido,
    registrado_por,
    sucursal_id
FROM gastos;


--  VISTAS 5 GABRIEL
CREATE OR REPLACE VIEW vw_gastos_por_sucursal AS
SELECT 
    id_gasto,
    descripcion,
    monto,
    categoria,
    fecha_ocurrido,
    sucursal_id
FROM gastos;



--  VISTAS 6 GABRIEL
SELECT * FROM vw_gastos_por_sucursal
WHERE sucursal_id = p_sucursal_id
ORDER BY fecha_ocurrido DESC;



--  VISTAS  7 GABRIEL
CREATE OR REPLACE VIEW vw_aperturas_caja AS
SELECT 
    id_apertura,
    caja_id,
    monto_inicial,
    fecha_apertura,
    estado
FROM aperturas_caja;



--  VISTAS 8 GABRIEL
CREATE OR REPLACE VIEW vw_sucursales AS
SELECT 
    sucursal_id,
    nombre,
    caja_id
FROM sucursal;



--  VISTAS 9 GABRIEL
CREATE OR REPLACE VIEW vw_ingresos_por_apertura AS
SELECT 
    a.id_apertura,
    i.descripcion,
    i.monto,
    i.fecha_recibido
FROM ingresos i
JOIN sucursal s ON i.sucursal_id = s.sucursal_id
JOIN aperturas_caja a ON s.caja_id = a.caja_id;



--  VISTAS 10 GABRIEL
CREATE OR REPLACE VIEW vw_gastos_por_apertura AS
SELECT 
    a.id_apertura,
    g.descripcion,
    g.monto,
    g.fecha_ocurrido
FROM gastos g
JOIN sucursal s ON g.sucursal_id = s.sucursal_id
JOIN aperturas_caja a ON s.caja_id = a.caja_id;



--  VISTAS 1 ANDREY
CREATE OR REPLACE VIEW V_USUARIOS_ACTIVOS AS
SELECT 
    USUARIO_ID,
    EMAIL,
    NOMBRE,
    ACTIVO,
    CREADO_EN,
    ACTUALIZADO_EN
FROM USUARIOS
WHERE ACTIVO = 1
ORDER BY CREADO_EN DESC;




--  VISTAS 2 ANDREY
CREATE OR REPLACE VIEW V_USUARIOS_CON_ROLES AS
SELECT 
    U.USUARIO_ID,
    U.NOMBRE AS USUARIO,
    U.EMAIL,
    R.ID_ROL,
    R.NOMBRE AS ROL,
    R.DESCRIPCION AS DESCRIPCION_ROL,
    UR.FECHA_ASIGNACION,
    UA.NOMBRE AS ASIGNADO_POR,
    UR.ACTIVO
FROM USUARIOS U
LEFT JOIN USUARIO_ROLES UR ON U.USUARIO_ID = UR.USUARIO_ID
LEFT JOIN ROLES R ON UR.ROL_ID = R.ROL_ID
LEFT JOIN USUARIOS UA ON UR.ASIGNADO_POR = UA.USUARIO_ID
WHERE U.ACTIVO = 1;



--  VISTAS 3 ANDREY
CREATE OR REPLACE VIEW V_DIRECCIONES_USUARIOS AS
SELECT 
    D.ID_DIRECCION,
    U.USUARIO_ID,
    U.NOMBRE AS USUARIO,
    U.EMAIL,
    D.ETIQUETA,
    D.NOMBRE_DESTINATARIO,
    D.LINEA_1,
    D.CIUDAD,
    D.PROVINCIA,
    D.CODIGO_POSTAL,
    D.PAIS,
    D.TELEFONO,
    D.CREADO_EN
FROM DIRECCIONES_USUARIO D
JOIN USUARIOS U ON D.USUARIO_ID = U.USUARIO_ID
WHERE U.ACTIVO = 1;




--  VISTAS 4 ANDREY
CREATE OR REPLACE VIEW V_AUDITORIA_USUARIOS AS
SELECT 
    U.USUARIO_ID,
    U.NOMBRE,
    U.EMAIL,
    U.ACTIVO,
    U.CREADO_EN,
    U.ACTUALIZADO_EN,
    (SELECT COUNT(*) FROM DIRECCIONES_USUARIO WHERE USUARIO_ID = U.USUARIO_ID) AS TOTAL_DIRECCIONES,
    (SELECT COUNT(*) FROM USUARIO_ROLES WHERE USUARIO_ID = U.USUARIO_ID AND ACTIVO = 1) AS TOTAL_ROLES,
    ROUND(SYSDATE - U.CREADO_EN) AS DIAS_REGISTRADO
FROM USUARIOS U
ORDER BY U.CREADO_EN DESC;



--  VISTAS 1 JOSE
CREATE OR REPLACE VIEW VW_PRODUCTOS_ACTIVOS AS
SELECT P.ID_PRODUCTO,
       P.SKU,
       P.NOMBRE,
       C.NOMBRE AS CATEGORIA,
       P.ACTIVO
FROM PRODUCTOS P
LEFT JOIN CATEGORIA C ON P.CATEGORIA_ID = C.CATEGORIA_ID
WHERE P.ACTIVO = 1;




--  VISTAS 2 JOSE
CREATE OR REPLACE VIEW VW_STOCK_BODEGA AS
SELECT B.NOMBRE AS BODEGA,
       P.NOMBRE AS PRODUCTO,
       PB.CANTIDAD_DISPONIBLE,
       PB.CANTIDAD_RESERVADA,
       PB.CANTIDAD_ALERTA
FROM PRODUCTOXBODEGA PB
JOIN PRODUCTOS P ON PB.PRODUCTO_ID = P.ID_PRODUCTO
JOIN BODEGA B ON PB.BODEGA_ID = B.BODEGA_ID;




--  VISTAS 3 JOSE
CREATE OR REPLACE VIEW VW_ORDENES_USUARIO AS
SELECT O.ID_ORDEN,
       O.NUMERO_ORDEN,
       O.ESTADO,
       O.TOTAL,
       U.NOMBRE AS USUARIO
FROM ORDENES O
JOIN USUARIOS U ON O.USUARIO_ID = U.USUARIO_ID;




--  VISTAS 4 JOSE
CREATE OR REPLACE VIEW VW_FACTURAS_DETALLE AS
SELECT F.ID_FACTURA,
       F.NUMERO_FACTURA,
       F.TOTAL,
       F.DESCUENTOS,
       F.FECHA_EMISION,
       O.NUMERO_ORDEN
FROM FACTURAS F
LEFT JOIN ORDENES O ON F.ORDEN_ID = O.ID_ORDEN;



--  VISTAS 5 JOSE
CREATE OR REPLACE VIEW VW_BODEGAS_ACTIVAS AS
SELECT B.BODEGA_ID,
       B.NOMBRE,
       B.CODIGO,
       S.NOMBRE AS SUCURSAL
FROM BODEGA B
JOIN SUCURSAL S ON B.SUCURSAL_ID = S.SUCURSAL_ID
WHERE B.ACTIVO = 1;




----------------------------------------------------
----------------------------------------------------
--  FUNCIONES FUNCIONES FUNCIONES FUNCIONES............. FUNCIONES HAY 5
----------------------------------------------------
----------------------------------------------------


-- FUNCION 1 ANDREY
CREATE OR REPLACE FUNCTION FN_EMAIL_DISPONIBLE(
    p_email VARCHAR2,
    p_usuario_id NUMBER DEFAULT NULL
) RETURN NUMBER
AS
    v_count NUMBER := 0;
BEGIN
    IF p_usuario_id IS NULL THEN
        SELECT COUNT(*) INTO v_count
        FROM USUARIOS
        WHERE EMAIL = p_email;
    ELSE
        SELECT COUNT(*) INTO v_count
        FROM USUARIOS
        WHERE EMAIL = p_email
        AND USUARIO_ID != p_usuario_id;
    END IF;
    
    IF v_count = 0 THEN
        RETURN 1; -- email disponible
    ELSE
        RETURN 0; -- email no disponible
    END IF;
END FN_EMAIL_DISPONIBLE;


-- FUNCION 2 ANDREY
CREATE OR REPLACE FUNCTION FN_OBTENER_NOMBRE_USUARIO(
    p_usuario_id NUMBER
) RETURN VARCHAR2
AS
    v_nombre VARCHAR2(100);
BEGIN
    SELECT NOMBRE INTO v_nombre
    FROM USUARIOS
    WHERE USUARIO_ID = p_usuario_id;
    
    RETURN v_nombre;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Usuario no encontrado';
END FN_OBTENER_NOMBRE_USUARIO;


-- FUNCION 3 ANDREY
CREATE OR REPLACE FUNCTION FN_CONTAR_DIRECCIONES_USUARIO(
    p_usuario_id NUMBER
) RETURN NUMBER
AS
    v_total NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_total
    FROM DIRECCIONES_USUARIO
    WHERE USUARIO_ID = p_usuario_id;
    
    RETURN v_total;
END FN_CONTAR_DIRECCIONES_USUARIO;
/

-- FUNCION 4 ANDREY
CREATE OR REPLACE FUNCTION FN_FORMATEAR_DIRECCION_COMPLETA(
    p_direccion_id NUMBER
) RETURN VARCHAR2
AS
    v_direccion VARCHAR2(500);
BEGIN
    SELECT LINEA_1 || ', ' || CIUDAD || ', ' || PROVINCIA || ', ' || PAIS
    INTO v_direccion
    FROM DIRECCIONES_USUARIO
    WHERE ID_DIRECCION = p_direccion_id;
    
    RETURN v_direccion;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Direccion no encontrada';
END FN_FORMATEAR_DIRECCION_COMPLETA;


-- FUNCION 5 ANDREY
CREATE OR REPLACE FUNCTION FN_USUARIO_TIENE_ROL(
    p_usuario_id NUMBER,
    p_nombre_rol VARCHAR2
) RETURN NUMBER
AS
    v_tiene_rol NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_tiene_rol
    FROM USUARIO_ROLES UR
    JOIN ROLES R ON UR.ROL_ID = R.ROL_ID
    WHERE UR.USUARIO_ID = p_usuario_id
    AND R.NOMBRE = p_nombre_rol
    AND UR.ACTIVO = 1;
    
    IF v_tiene_rol > 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END FN_USUARIO_TIENE_ROL;


-- 1.FUNCION JOSE

CREATE OR REPLACE FUNCTION FN_NOMBRE_PRODUCTO (
    P_ID_PRODUCTO NUMBER
) RETURN VARCHAR2
AS
    V_NOMBRE VARCHAR2(255);
BEGIN
    SELECT NOMBRE INTO V_NOMBRE
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;

    RETURN V_NOMBRE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
END FN_NOMBRE_PRODUCTO;


-- 2. FUNCION JOSE

CREATE OR REPLACE FUNCTION FN_TOTAL_FACTURA (
    P_ID_FACTURA NUMBER
) RETURN NUMBER
AS
    V_TOTAL NUMBER;
BEGIN
    SELECT TOTAL INTO V_TOTAL
    FROM FACTURAS
    WHERE ID_FACTURA = P_ID_FACTURA;

    RETURN V_TOTAL;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_TOTAL_FACTURA;

-- 3. FUNCION JOSE

CREATE OR REPLACE FUNCTION FN_STOCK_BODEGA (
    P_PRODUCTO_ID NUMBER,
    P_BODEGA_ID NUMBER
) RETURN NUMBER
AS
    V_STOCK NUMBER;
BEGIN
    SELECT CANTIDAD_DISPONIBLE INTO V_STOCK
    FROM PRODUCTOXBODEGA
    WHERE PRODUCTO_ID = P_PRODUCTO_ID
      AND BODEGA_ID = P_BODEGA_ID;

    RETURN V_STOCK;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_STOCK_BODEGA;


-- 4. FUNCION JOSE

CREATE OR REPLACE FUNCTION FN_CUPON_ACTIVO (
    P_ID_CUPON NUMBER
) RETURN NUMBER
AS
    V_ACT NUMBER;
BEGIN
    SELECT ACTIVO INTO V_ACT
    FROM CUPONES
    WHERE ID_CUPON = P_ID_CUPON;

    RETURN V_ACT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_CUPON_ACTIVO;


-- 5. FUNCION JOSE

CREATE OR REPLACE FUNCTION FN_CATEGORIA_PRODUCTO (
    P_ID_PRODUCTO NUMBER
) RETURN VARCHAR2
AS
    V_CATEGORIA VARCHAR2(255);
BEGIN
    SELECT C.NOMBRE INTO V_CATEGORIA
    FROM PRODUCTOS P
    JOIN CATEGORIA C ON P.CATEGORIA_ID = C.CATEGORIA_ID
    WHERE P.ID_PRODUCTO = P_ID_PRODUCTO;

    RETURN V_CATEGORIA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
END FN_CATEGORIA_PRODUCTO;


-- CURSORES DE INVENTARIO JOSE

-- 1. CURSOR: Productos activos

DECLARE
    CURSOR CUR_PRODUCTOS_ACTIVOS RETURN PRODUCTOS%ROWTYPE IS
        SELECT *
        FROM PRODUCTOS
        WHERE ACTIVO = 1;

    V_PROD PRODUCTOS%ROWTYPE;
BEGIN
    OPEN CUR_PRODUCTOS_ACTIVOS;
    LOOP
        FETCH CUR_PRODUCTOS_ACTIVOS INTO V_PROD;
        EXIT WHEN CUR_PRODUCTOS_ACTIVOS%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Producto: ' || V_PROD.NOMBRE ||
            ' | Precio: ' || V_PROD.PRECIO
        );
    END LOOP;
    CLOSE CUR_PRODUCTOS_ACTIVOS;
END;


-- 2. CURSOR: Productos con stock en alerta

DECLARE
    CURSOR CUR_STOCK_ALERTA RETURN PRODUCTOXBODEGA%ROWTYPE IS
        SELECT *
        FROM PRODUCTOXBODEGA
        WHERE CANTIDAD_DISPONIBLE <= CANTIDAD_ALERTA;

    V_ROW PRODUCTOXBODEGA%ROWTYPE;
BEGIN
    OPEN CUR_STOCK_ALERTA;
    LOOP
        FETCH CUR_STOCK_ALERTA INTO V_ROW;
        EXIT WHEN CUR_STOCK_ALERTA%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Producto: ' || V_ROW.PRODUCTO_ID ||
            ' | Stock: ' || V_ROW.CANTIDAD_DISPONIBLE ||
            ' | Alerta: ' || V_ROW.CANTIDAD_ALERTA
        );
    END LOOP;
    CLOSE CUR_STOCK_ALERTA;
END;
/

-- 3. CURSOR: Bodegas activas

DECLARE
    CURSOR CUR_BODEGAS_ACTIVAS RETURN BODEGA%ROWTYPE IS
        SELECT *
        FROM BODEGA
        WHERE ACTIVO = 1;

    V_BOD BODEGA%ROWTYPE;
BEGIN
    OPEN CUR_BODEGAS_ACTIVAS;
    LOOP
        FETCH CUR_BODEGAS_ACTIVAS INTO V_BOD;
        EXIT WHEN CUR_BODEGAS_ACTIVAS%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Bodega: ' || V_BOD.NOMBRE ||
            ' | Ubicacion: ' || V_BOD.UBICACION
        );
    END LOOP;
    CLOSE CUR_BODEGAS_ACTIVAS;
END;
/

-- 4. CURSOR: Productos sin stock

DECLARE
    CURSOR CUR_PRODUCTOS_SIN_STOCK RETURN PRODUCTOXBODEGA%ROWTYPE IS
        SELECT *
        FROM PRODUCTOXBODEGA
        WHERE CANTIDAD_DISPONIBLE = 0;

    V_ROW PRODUCTOXBODEGA%ROWTYPE;
BEGIN
    OPEN CUR_PRODUCTOS_SIN_STOCK;
    LOOP
        FETCH CUR_PRODUCTOS_SIN_STOCK INTO V_ROW;
        EXIT WHEN CUR_PRODUCTOS_SIN_STOCK%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Producto sin stock: ' || V_ROW.PRODUCTO_ID ||
            ' | Bodega: ' || V_ROW.BODEGA_ID
        );
    END LOOP;
    CLOSE CUR_PRODUCTOS_SIN_STOCK;
END;
/

-- 5. CURSOR: Facturas recientes (ultimos 30 dias)

DECLARE
    CURSOR CUR_FACTURAS_RECIENTES RETURN FACTURAS%ROWTYPE IS
        SELECT *
        FROM FACTURAS
        WHERE FECHA_EMISION >= SYSDATE - 30;

    V_FAC FACTURAS%ROWTYPE;
BEGIN
    OPEN CUR_FACTURAS_RECIENTES;
    LOOP
        FETCH CUR_FACTURAS_RECIENTES INTO V_FAC;
        EXIT WHEN CUR_FACTURAS_RECIENTES%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Factura: ' || V_FAC.ID_FACTURA ||
            ' | Total: ' || V_FAC.TOTAL ||
            ' | Fecha: ' || TO_CHAR(V_FAC.FECHA_EMISION, 'DD-MM-YYYY')
        );
    END LOOP;
    CLOSE CUR_FACTURAS_RECIENTES;
END;